

/* tslint:disable */
// This file was automatically generated and should not be edited.

// ====================================================
// GraphQL query operation: GetRaceWithSourceId
// ====================================================

export interface GetRaceWithSourceId_race_contentsType_targetContent {
  __typename: "TargetContent";
  landingUrl: string | null;
  bannerUrl: string | null;  // Url without scheme
  altString: string | null;
}

export interface GetRaceWithSourceId_race_contentsType {
  __typename: "RaceContentsType";
  targetId: any | null;  // Generated by Management Tool
  targetContent: (GetRaceWithSourceId_race_contentsType_targetContent | null)[] | null;
}

export interface GetRaceWithSourceId_race {
  __typename: "Race";
  status: number | null;  // Status code ("91": Success)
  revision: string | null;
  contentsType: (GetRaceWithSourceId_race_contentsType | null)[] | null;
}

export interface GetRaceWithSourceId {
  race: (GetRaceWithSourceId_race | null)[] | null;
}

export interface GetRaceWithSourceIdVariables {
  sourceId: string;
  deviceType?: string | null;
}

/* tslint:disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

//==============================================================
// END Enums and Input Objects
//==============================================================